---
- name: Install software
  apt:
    name:
      - realmd
      - samba
      - chrony
      - packagekit
      - policykit-1
      - krb5-user

- name: Configure chrony
  template:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
  notify: Restart chrony

- name: Configure Kerberos
  template:
    src: krb5.conf
    dest: /etc/krb5.conf

- name: Configure samba
  template:
    src: smb.conf
    dest: /etc/samba/smb.conf
  notify:
    - Restart smbd
    - Restart nmbd

- name: Update hosts file
  template:
    src: hosts
    dest: /etc/hosts

- name: Update sshd_config
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  notify:
  - Restart sshd

- name: Update sudoers
  template:
    src: domain_sudoers
    dest: /etc/sudoers.d/domain_sudoers
    validate: 'visudo -cf %s'
    mode: 0440


- name: Update /etc/pam.d/common-session
  lineinfile:
    path: /etc/pam.d/common-session
    insertafter: session\s+required\s+pam_unix\.so
    line: session required pam_mkhomedir.so skel=/etc/skel/ umask=0022

- name: Check domain membership
  shell:
    cmd: realm list {{ad_realm|lower}}
  register: realm_list_result

- name: Join domain
  include: join_domain.yml
  when: '"configured: kerberos-member" in realm_list_result.stdout'

- name: Finalize sssd config
  lineinfile:
    path: /etc/sssd/sssd.conf
    insertafter: \[domain/{{ad_realm|lower|replace('.', '\.')}}\]
    regex: "{{item.regex}}"
    line: "{{item.line}}"
  with_items:
    - line: use_fully_qualified_names = False
      regex: use_fully_qualified_names\s*=.*
    - line: override_shell = /bin/bash
      regex: override_shell\s*=.*
    - line: override_homedir = /home/%d/%u
      regex: override_homedir\s*=.*
    - line: dyndns_iface = {{ad_dyndns_iface}}
      regex: dyndns_iface\s*=.*
  notify:
    - Restart sssd
