---
- name: Restart smbd
  service:
    name: smbd
    state: restarted
    enabled: yes

- name: Restart nmbd
  service:
    name: nmbd
    state: restarted
    enabled: yes

- name: Restart chrony
  service:
    name: chrony
    state: restarted
    enabled: yes

- name: Restart sssd
  service:
    name: sssd
    state: restarted
    enabled: yes