---
- name: Restart chrony
  service:
    name: chrony
    state: restarted
    enabled: yes

- name: Restart sssd
  service:
    name: sssd
    state: restarted
    enabled: yes

- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes